defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  5570d265-1c68-493e-9d8d-b625a29ddfed: # pairadice
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
